{% set name = "simpful" %}
{% set version = "2.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/simpful-{{ version }}.tar.gz
  sha256: 935c4f179a0b067a055cac81917229d11e89b949a73db969ca9bd2a804f5bc7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.12.0
    - scipy >=1.0.0

test:
  imports:
    - simpful
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aresio/simpful
  summary: A user-friendly Python library for fuzzy logic
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hechth
    - aresio
    - sspola
